trigger:
  branches:
    include:
      - master
  paths:
    include:
      - /aws-terpoc/main.tf
pool:
  vmImage: "ubuntu-latest"
steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: 'Install Terraform 0.12.3'
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform : aws init'
  inputs:
    provider: aws
    workingDirectory: 'aws-terpoc'
    backendServiceAWS: 'aws-azure-terr-conct'
    backendAWSBucketName: 'terpoc-s3buck'
    backendAWSKey: global/terraform.tfstate
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform : aws validate'
  inputs:
    provider: aws
    command: validate
    workingDirectory: 'aws-terpoc'  
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform : aws plan'
  inputs:
    provider: aws
    command: plan
    workingDirectory: 'aws-terpoc'
    environmentServiceNameAWS: 'aws-azure-terr-conct'
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform : vm apply'
  inputs:
    provider: aws
    command: apply
    workingDirectory: 'aws-terpoc'
    environmentServiceNameAWS: 'aws-azure-terr-conct'